### ISSUE TITLE
Windows 扫描 node_modules 程序卡死

### ISSUE THREAD

**Issue by wuyiya** [d2-projects/folder-explorer#1]
win7系统下 导入带有node_modules的目录软件卡死 必须通过任务管理器杀掉才能重启软件

**Comment by FairyEver** [comment]
https://github.com/d2-projects/folder-explorer/blob/5c1fdef693deafa77dfe56daf133d2677b4ce0c1/src/store.js#L174

是这里的问题。因为我是 macOS，我的目录分隔符（`/`）和 Windows（`\`） 不一样，忽略了这个点。默认的设置在 macOS 上是会自动忽略 node_modules 的。

<img width="912" alt="Xnip2019-09-27_18-20-36" src="https://user-images.githubusercontent.com/19357920/65762405-86b42980-e153-11e9-954e-047c201471ba.png">

你可以先手动在设置里加上 `\node_modules`。
